### PR TITLE
test: verification of time range filters in payment operations page using cypress

### PR DESCRIPTION
**Pull request by s-vamshi**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Verification of time range filters in payment operations page using cypress by following steps provided in the issue

## Motivation and Context
resolves [#6129](https://github.com/juspay/hyperswitch/issues/6129)

## Where to test it?

- [ ] INTEG
- [ ] SANDBOX
- [ ] PROD

## Checklist

- [ ] I ran `npm run re:build`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

**Comment by s-vamshi** [comment]
hey @JeevaRamu0104  @gorakhnathy7 can you please review this pr in your free time?

**Comment by s-vamshi** [comment]
@JeevaRamu0104 added demo video for this test case
https://github.com/user-attachments/assets/3d85b4e5-1e7b-4e36-82d1-a1fbfb901a6b

**Comment by JeevaRamu0104** [comment]
Hi @s-vamshi tests are not working as expected please check it again.
image

**Comment by s-vamshi** [comment]
hi @JeevaRamu0104, made changes and squashed them, can you please review them in your free time?

**Pull request merged**
