### PR TITLE
test: creation of test payment using sdk cypress

### PR DESCRIPTION
**Pull request by s-vamshi**
## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

creation of test payment using sdk cypress by following the steps mentioned in the issue

## Motivation and Context

Resolves [#6124](https://github.com/juspay/hyperswitch/issues/6124)

## Where to test it?

- [ ] INTEG
- [ ] SANDBOX
- [ ] PROD

## Checklist

- [ ] I ran `npm run re:build`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

**Review by JeevaRamu0104 — COMMENTED** [review]
please resolve the conflicts and also attach the working video

**Comment by s-vamshi** [comment]
Sure will do that!

**Review by JeevaRamu0104 — COMMENTED** [review]
@s-vamshi while testing locally test were failing.Please re-check it.
image

**Comment by s-vamshi** [comment]
hey @JeevaRamu0104, here is the working video
https://github.com/user-attachments/assets/e7efd4b8-69b2-4053-9496-c99d8d605182

**Comment by s-vamshi** [comment]
@JeevaRamu0104 @racnan can you please review this pr?

**Comment by s-vamshi** [comment]
Hey @gorakhnathy7 can you please check this pr?

**Pull request merged**
