### PR TITLE
feat: Remove user-management revamp feature flag

### PR DESCRIPTION
**Pull request by Riddhiagrawal001**
## Type of Change

- [ ] Bugfix
- [X] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

Removed old user module and removed `user-management-revamp` feature flag

## How did you test it?
New modules should be available in the dashboard and should be working as expected

## Where to test it?

- [X] INTEG
- [X]  SANDBOX
- [X] PROD

## Checklist

- [ ] I ran `npm run re:build`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

### CODE REVIEW

**Review by PritishBudhiraja — APPROVED** [review]
Looks good 👍🏼

**Review by PritishBudhiraja — DISMISSED** [review]
✌️

**Review by PritishBudhiraja — APPROVED** [review]
✨✅

**Comment by Riddhiagrawal001** [comment]
Please verify by running the changes locally and ensure that the new user module remains unaffected by this modification.

**Review by JeevaRamu0104 — DISMISSED** [review]

**Review by gitanjli525 — APPROVED** [review]

**Review by PritishBudhiraja — APPROVED** [review]

**Review by JeevaRamu0104 — APPROVED** [review]

**Pull request merged**
